version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "playwright-tests"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-42foon6evgbm"
s3_prefix = "playwright-tests"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = [] 