name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'tests/**'
      - 'playwright.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - '.env.*'
      - 'scripts/**'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [stage, prod]
        region: [us-east-1, eu-west-2, ap-southeast-1]

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ matrix.region }}
    
    - name: Deploy to Lambda
      run: npm run deploy:lambda:${{ matrix.env }}
      env:
        AWS_REGION: ${{ matrix.region }} 