name: Release to dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    uses: cere-io/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:18-buster'
      install_packages_command: 'npm ci'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'build'
      aws_account_id: ${{ vars.DEV_CORE_AWS_ACCOUNT_ID }}
      s3_bucket_name: 'dev-cere-ddc-telegram-mini-app'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}