name: Run Playwright Tests

on:
  schedule:
    - cron: '0 9,18 * * *'
  workflow_dispatch:

jobs:
  vpn-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Set up OpenVPN (Germany)
        uses: marketplace-actions/openvpn-action@v1
        with:
          config: ./configs/de-12.protonvpn.tcp.ovpn
          username: ${{ secrets.PROTONVPN_USERNAME }}
          password: ${{ secrets.PROTONVPN_PASSWORD }}

      - name: Wait for VPN connection
        run: sleep 10 && curl ifconfig.me

      - name: Run Playwright tests (Germany)
        run: npx playwright test --project=Germany
