name: Release to prod
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    uses: cere-io/reusable-workflows/.github/workflows/deploy-to-cloudfront.yaml@master
    with:
      build_container: 'node:18-buster'
      install_packages_command: 'cp .env.prod .env; npm ci'
      build_command: 'npm run build'
      path_to_static_files_to_upload: 'dist'
      aws_account_id: ${{ vars.PRD_NETWORK_AWS_ACCOUNT_ID }}
      s3_bucket_name: 'telegram-miniapps.cere.io'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
