name: 'Tests'

on:
  pull_request:
  workflow_dispatch:

  push:
    branches:
      - dev
      - master

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Install packages
        run: npm ci

      - name: Check code style
        run: npm run lint

      - name: Check types
        run: npm run check-types

      - name: Build packages
        run: npm run build
